<?php


return [
    'flatrate' => [
        'code'         => 'flatrate',
        'icon'         => '',
        'title'        => 'Flat Rate',
        'description'  => 'Flat Rate Shipping',
        'active'       => false,
        'default_rate' => '10',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\FlatRate',
    ],

    'free' => [
        'code'         => 'free',
        'icon'         => '',
        'title'        => 'Free Shipping',
        'description'  => 'Free Shipping',
        'active'       => false,
        'default_rate' => '0',
        'class'        => 'Webkul\Shipping\Carriers\Free',
    ],
    'jneekonomi' => [
        'code'         => 'jneekonomi',
        'icon'         => 'https://deviloarts.com/wp-content/uploads/JNE-Express-Logo-Vector-1536x1087.jpg',
        'title'        => 'JNE EKonomi',
        'description'  => 'JNE EKonomi',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNEEkonomi',
    ],
    'jneregular' => [
        'code'         => 'jneregular',
        'icon'         => 'https://deviloarts.com/wp-content/uploads/JNE-Express-Logo-Vector-1536x1087.jpg',
        'title'        => 'JNE Regular',
        'description'  => 'JNE Regular',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNERegular',
    ],
    'jnespeed' => [
        'code'         => 'jnespeed',
        'icon'         => 'https://deviloarts.com/wp-content/uploads/JNE-Express-Logo-Vector-1536x1087.jpg',
        'title'        => 'JNE Speed',
        'description'  => 'JNE Speed',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNESpeed',
    ],
    'jneyes' => [
        'code'         => 'jneyes',
        'icon'         => 'https://deviloarts.com/wp-content/uploads/JNE-Express-Logo-Vector-1536x1087.jpg',
        'title'        => 'JNE YES',
        'description'  => 'JNE YES',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNEYes',
    ],
    'tikisatu' => [
        'code'         => 'tikisatu',
        'icon'         => 'https://3.bp.blogspot.com/-sq9MnKqpa9w/WbyeL--KFLI/AAAAAAAAElA/TCVZ4-9olckRE9L40kvVPQPkLoMp8zjdgCEwYBhgL/s1600/LOGO-TIKI.png',
        'title'        => 'TIKI SATU',
        'description'  => 'TIKI SATU',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\TIKISatu',
    ],
    'tikidua' => [
        'code'         => 'tikidua',
        'icon'         => 'https://3.bp.blogspot.com/-sq9MnKqpa9w/WbyeL--KFLI/AAAAAAAAElA/TCVZ4-9olckRE9L40kvVPQPkLoMp8zjdgCEwYBhgL/s1600/LOGO-TIKI.png',
        'title'        => 'TIKI dua',
        'description'  => 'TIKI dua',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\TIKIDua',
    ],
    'tikitiga' => [
        'code'         => 'tikitiga',
        'icon'         => 'https://3.bp.blogspot.com/-sq9MnKqpa9w/WbyeL--KFLI/AAAAAAAAElA/TCVZ4-9olckRE9L40kvVPQPkLoMp8zjdgCEwYBhgL/s1600/LOGO-TIKI.png',
        'title'        => 'TIKI Tiga',
        'description'  => 'TIKI Tiga',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\TIKITiga',
    ],
    'possatu' => [
        'code'         => 'possatu',
        'icon'         => 'https://banner2.cleanpng.com/20180706/pq/kisspng-pos-indonesia-persero-pt-joint-stock-company-ma-vector-peta-indonesia-5b3fd260567700.5007629815309092803542.jpg',
        'title'        => 'POS SAtu',
        'description'  => 'POS Satu',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\POSSatu',
    ],
    'posdua' => [
        'code'         => 'posdua',
        'icon'         => 'https://banner2.cleanpng.com/20180706/pq/kisspng-pos-indonesia-persero-pt-joint-stock-company-ma-vector-peta-indonesia-5b3fd260567700.5007629815309092803542.jpg',
        'title'        => 'POS Dua',
        'description'  => 'POS Dua',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\POSdua',
    ],
];
