<?php

return [
    'flatrate' => [
        'code'         => 'flatrate',
        'title'        => 'Flat Rate',
        'description'  => 'Flat Rate Shipping',
        'active'       => false,
        'default_rate' => '10',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\FlatRate',
    ],

    'free' => [
        'code'         => 'free',
        'title'        => 'Free Shipping',
        'description'  => 'Free Shipping',
        'active'       => false,
        'default_rate' => '0',
        'class'        => 'Webkul\Shipping\Carriers\Free',
    ],
    'jneekonomi' => [
        'code'         => 'jneekonomi',
        'title'        => 'JNE EKonomi',
        'description'  => 'JNE EKonomi',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNEEkonomi',
    ],
    'jneregular' => [
        'code'         => 'jneregular',
        'title'        => 'JNE Regular',
        'description'  => 'JNE Regular',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNERegular',
    ],
    'jnespeed' => [
        'code'         => 'jnespeed',
        'title'        => 'JNE Speed',
        'description'  => 'JNE Speed',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNESpeed',
    ],
    'jneyes' => [
        'code'         => 'jneyes',
        'title'        => 'JNE YES',
        'description'  => 'JNE YES',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\JNEYes',
    ],
    'tikisatu' => [
        'code'         => 'tikisatu',
        'title'        => 'TIKI SATU',
        'description'  => 'TIKI SATU',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\TIKISatu',
    ],
    'tikidua' => [
        'code'         => 'tikidua',
        'title'        => 'TIKI dua',
        'description'  => 'TIKI dua',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\TIKIDua',
    ],
    'tikitiga' => [
        'code'         => 'tikitiga',
        'title'        => 'TIKI Tiga',
        'description'  => 'TIKI Tiga',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\TIKITiga',
    ],
    'possatu' => [
        'code'         => 'possatu',
        'title'        => 'POS SAtu',
        'description'  => 'POS Satu',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\POSSatu',
    ],
    'posdua' => [
        'code'         => 'posdua',
        'title'        => 'POS Dua',
        'description'  => 'POS Dua',
        'active'       => true,
        'default_rate' => '0',
        'type'         => 'per_unit',
        'class'        => 'Webkul\Shipping\Carriers\POSdua',
    ],
];
